### PR TITLE
Fix for tables that have no primary key

### LINKED ISSUE #8: When no primary key is defined on a table during `.createTable` things blow up
Found this today while running migrations from 2 years ago on a build server.

https://github.com/db-migrate/db-migrate-base/blob/master/index.js#L207

If you define a table that doesn't have a column as a primary key, this will fail. Having a table with no primary key is not always standard but it is a thing.

I will submit a PR that fixes this shortly.

### PR DESCRIPTION
**Pull request by mikemimik**
Fixes #8

### CODE REVIEW

**Comment by mikemimik** [comment]
@wzrdtales 
Don't mean to bug, just not sure how your github notification settings are setup for the `db-migrate` org.

**Comment by wzrdtales** [comment]
@mikemimik No problem here, don't be afraid to hit me up, if you don't get an answer in a timely fashion though :)

File: index.js [hunk 1]
```diff
@@ -199,13 +199,13 @@ var Base = Class.extend({
...
 
     var pkSql = '';
-    if (primaryKeyColumns.length > 1) {
-      pkSql = this._handleMultiPrimaryKeys(primaryKeyColumns);
-
-    } else {
-
-      primaryKeyColumns[0] = primaryKeyColumns[0].name;
-      columnDefOptions.emitPrimaryKey = true;
+    if (primaryKeyColumns.length) {
```
Comment (wzrdtales) [inline index.js:202]: How is this supposed to solve a problem?
https://github.com/db-migrate/db-migrate-base/blob/master/index.js#L188

As you can see primaryKeyColumns is never undefined though.

Comment (wzrdtales) [reply index.js:202]: Ah ok now I understand, wasn't clear from the beginning.

But instead of doing this I suggest checking that length is greater than 0, as this makes more sense then checking if the variable is somehow initialized and the reader understands the intention.

**Review by wzrdtales — CHANGES_REQUESTED** [review]

File: index.js (hunk 1 above)
Comment (mikemimik) [reply index.js:202]:
```javascript
const array = [];
if (array.length > 0) {
 // do something
}
```
Is fundamentally the same as:
```javascript
const array = [];
if (array.length) {
 // do something
}
```

I do understand that the former is more readable, so if you'd very much like me to change it I will. However the latter is more succinct.

Comment (mikemimik) [reply index.js:202]: @wzrdtales I'm just re-reading this now. Do you mean in the second `if` to change the `else` into an `else if`?

Comment (wzrdtales) [reply index.js:202]: This is also an option and I do not think that your version is more succinct b/c it is ambiguous. Both are an option though, checking in the else tree is one and checking from above is one. Actually doing it on the else tree would be one comparison less to be processed in the optimistic case, so generally also a good option to go for, although branch prediction probably diminishs the effect anyway :)
